### ISSUE TITLE
Too Much Parallelism!

### ISSUE THREAD

**Issue by anillohchab** [JChrist/gitextender#55]
Hey,

Thanks a lot for the awesome plugin. Its life, as well as a time saver :)

In my project I have generally bunch of repositories 10s sometime 20s in my project.  Whenever I run sync "Git Extender > Update All" its gets throttled  bunch of time. I had to keep retrying until it succeeds, creating more traffic. So, I was wondering if I could "slow" it down to do the sync. Do you think its something we could do ? 

I was thinking `GitExtenderUpdateAll.updateRepositories` specifically around [this](https://github.com/JChrist/gitextender/blob/main/src/main/java/gr/jchrist/gitextender/GitExtenderUpdateAll.java#L125-L129). Probably change this to go through each thread sequentially and wait for that to finish before starting the next. What do you think ? 

Thanks,
-anil

**Comment by JChrist** [comment]
Hi @anillohchab.
Is this still an issue you're facing?
You are right, that line is the cause of your problems, as a new thread is started for each of your repos.
Instead of starting a new thread for each repo, a thread pool could be used with a fixed number of threads. I'm thinking that setting the thread pool size to `Math.min(repositories.size(), 3)` would be helpful for current users and users with too many repos.
